const T=window.SITE_TEXT;
const DEFAULT_DISHES=[];
const EMOJIS=["🍅","🐟","🍝","🍗","🌶️","🥣","🍰","🎁","🥩","🍖","🍤","🍣","🍛","🍚","🍜","🥟","🥗","🍲","🥘","🥪","🍕","🍔","🌮","🍓","🍮","🧁","☕","🧋"];
const STORE_ORDERS="love-kitchen-calendar-v2",STORE_MENU="love-kitchen-custom-menu-v2";
const today=new Date();today.setHours(12,0,0,0);
const state={page:"calendar",cursor:new Date(today.getFullYear(),today.getMonth(),1,12),selected:key(today),editor:null,dishEditor:null,orders:read(STORE_ORDERS,{}),menu:read(STORE_MENU,DEFAULT_DISHES)};
const app=document.querySelector("#app");
function key(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function fromKey(k){const[y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d,12)}
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||"null")||f}catch{return f}}
function persist(){localStorage.setItem(STORE_ORDERS,JSON.stringify(state.orders));localStorage.setItem(STORE_MENU,JSON.stringify(state.menu))}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function human(k){const d=fromKey(k);return`${d.getMonth()+1}月${d.getDate()}日 · ${["周日","周一","周二","周三","周四","周五","周六"][d.getDay()]}`}
function dish(id){return state.menu.find(x=>x.id===id)}
function orderNames(o){return(o?.dishes||[]).map(id=>dish(id)?.name||"已删除菜品")}
function header(){return`<header class="topbar"><div class="brand"><span>♥</span><div><strong>${T.brand}</strong><small>${T.brandEnglish}</small></div></div><nav><button data-page="calendar" class="${state.page==="calendar"?"active":""}">▦ ${T.calendarTab}</button><button data-page="menu" class="${state.page==="menu"?"active":""}">☷ ${T.menuTab}</button></nav><button class="primary compact" data-action="create">＋ ${T.newOrder}</button></header>`}
function cells(){const y=state.cursor.getFullYear(),m=state.cursor.getMonth(),start=new Date(y,m,1-new Date(y,m,1,12).getDay(),12);return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}
function calendar(){return`<section class="welcome"><span>${T.greeting}</span><h1>${T.subtitle}</h1></section><div class="calendar-layout"><section class="card calendar-card"><div class="calendar-head"><div><small>${T.calendarLabel}</small><h2>${state.cursor.getFullYear()}年 ${state.cursor.getMonth()+1}月</h2></div><div><button data-action="today">${T.today}</button><button data-action="prev">‹</button><button data-action="next">›</button></div></div><div class="week">${["日","一","二","三","四","五","六"].map(x=>`<span>${x}</span>`).join("")}</div><div class="month">${cells().map(d=>{const k=key(d),o=state.orders[k];return`<button data-date="${k}" class="day ${d.getMonth()!==state.cursor.getMonth()?"muted":""} ${k===key(today)?"today":""} ${k===state.selected?"selected":""}"><b>${d.getDate()}</b>${o?`<i class="status ${o.done?"done":""}">${o.done?"✓":""}</i><small>${orderNames(o)[0]}</small>`:""}</button>`}).join("")}</div><footer class="calendar-legend"><span><i></i>${T.pending}</span><span><i class="done">✓</i>${T.completed}</span><small>${T.calendarHint}</small></footer></section>${dayPanel()}</div>${upcoming()}`}
function dayPanel(){const o=state.orders[state.selected];if(!o)return`<aside class="card day-panel"><time>${human(state.selected)}</time><div class="empty"><span>🍽️</span><h2>${T.emptyTitle}</h2><p>${T.emptyBody}</p><button class="primary" data-action="create">＋ ${T.createOrder}</button></div></aside>`;return`<aside class="card day-panel"><time>${human(state.selected)}</time><div class="badge ${o.done?"done":""}">${o.done?"✓ "+T.completed:"● "+T.pending}</div><h2>${o.done?T.completedTitle:T.pendingTitle}</h2><div class="selected-dishes">${o.dishes.map(id=>{const d=dish(id);return d?`<div><span>${d.emoji}</span><strong>${esc(d.name)}</strong></div>`:""}).join("")}</div><div class="note"><small>${T.noteLabel}</small><p>${esc(o.note)||T.defaultNote}</p></div><div class="panel-buttons"><button data-action="edit">${T.editOrder}</button><button class="primary" data-action="toggle">${o.done?T.markPending:T.markCompleted} ✓</button></div><button class="delete" data-action="delete">${T.deleteOrder}</button></aside>`}
function upcoming(){const rows=Object.entries(state.orders).filter(([k,o])=>k>=key(today)&&!o.done).sort(([a],[b])=>a.localeCompare(b)).slice(0,3);return`<section class="card upcoming"><div><small>${T.upcomingLabel}</small><h2>${T.upcomingTitle}</h2></div>${rows.length?`<div class="upcoming-list">${rows.map(([k,o])=>`<button data-jump="${k}"><time><b>${fromKey(k).getDate()}</b>${fromKey(k).getMonth()+1}月</time><span><strong>${orderNames(o).join(" · ")}</strong><small>${esc(o.note)||T.chefPreparing}</small></span><i>›</i></button>`).join("")}</div>`:`<p>${T.upcomingEmpty}</p>`}</section>`}
function menuPage(){return`<section class="page-head"><div><small>MY MENU</small><h1>${T.menuTitle}</h1><p>${T.menuSubtitle}</p></div>${state.menu.length?`<button class="primary" data-action="add-dish">＋ ${T.addDish}</button>`:""}</section>${state.menu.length?`<section class="menu-grid">${state.menu.map(d=>`<article class="menu-card"><span>${d.emoji}</span><div><h3>${esc(d.name)}</h3><p>${esc(d.detail)}</p></div><div><button data-edit-dish="${d.id}">${T.editDish}</button><button class="danger" data-remove-dish="${d.id}">${T.deleteDish}</button></div></article>`).join("")}<button class="add-menu-card" data-action="add-dish"><span>＋</span><strong>${T.addDish}</strong><small>${T.chooseEmoji} · ${T.dishName}</small></button></section>`:`<section class="menu-empty"><div class="empty-add">＋</div><h2>${T.menuEmptyTitle}</h2><p>${T.menuEmptyBody}</p><button class="primary" data-action="add-dish">＋ ${T.addDish}</button></section>`}`}
function orderModal(){if(!state.editor)return"";const e=state.editor;return`<div class="overlay"><div class="modal"><header><div><small>${T.orderEditorLabel}</small><h2>${human(e.date)}，${T.orderEditorTitle}</h2></div><button data-action="cancel">×</button></header><label class="date-input"><span>${T.dateLabel}</span><input id="order-date" type="date" value="${e.date}"></label>${state.menu.length?`<div class="dish-choices">${state.menu.map(d=>`<button data-pick="${d.id}" class="${e.dishes.includes(d.id)?"picked":""}"><span>${d.emoji}</span><b>${esc(d.name)}</b><small>${esc(d.detail)}</small><i>${e.dishes.includes(d.id)?"✓":"+"}</i></button>`).join("")}</div><label class="textarea"><span>${T.noteEditorLabel}</span><textarea id="order-note" maxlength="120" placeholder="${T.notePlaceholder}">${esc(e.note)}</textarea></label><p class="error">${e.error||""}</p><footer><button data-action="cancel">${T.cancel}</button><button class="primary" data-action="save-order">${T.saveOrder} ♥</button></footer>`:`<div class="order-no-menu"><span>🍽️</span><h3>${T.menuEmptyTitle}</h3><p>${T.menuEmptyBody}</p><button class="primary" data-action="go-menu">${T.addDish}</button></div>`}</div></div>`}
function dishModal(){if(!state.dishEditor)return"";const e=state.dishEditor;return`<div class="overlay"><div class="modal dish-modal"><header><div><small>MENU ITEM</small><h2>${e.id?T.editDish:T.addDish}</h2></div><button data-action="cancel-dish">×</button></header><label class="field"><span class="visually-hidden">${T.dishName}</span><input id="dish-name" value="${esc(e.name)}" maxlength="30" placeholder="${T.dishName}" aria-label="${T.dishName}"></label><label class="field"><span class="visually-hidden">${T.dishDescription}</span><input id="dish-detail" value="${esc(e.detail)}" maxlength="50" placeholder="${T.dishDescription}" aria-label="${T.dishDescription}"></label><div class="emoji-picker"><span>${T.chooseEmoji}</span><div>${EMOJIS.map(x=>`<button data-emoji="${x}" class="${e.emoji===x?"active":""}">${x}</button>`).join("")}</div></div><p class="error">${e.error||""}</p><footer><button data-action="cancel-dish">${T.cancel}</button><button class="primary" data-action="save-dish">${T.saveDish}</button></footer></div></div>`}
function render(){app.innerHTML=`<main class="shell">${header()}${state.page==="calendar"?calendar():menuPage()}<footer class="footer">${T.footer} <span>♥</span></footer></main><nav class="mobile-nav"><button data-page="calendar" class="${state.page==="calendar"?"active":""}">▦<span>${T.calendarTab}</span></button><button data-action="create">＋<span>${T.newOrder}</span></button><button data-page="menu" class="${state.page==="menu"?"active":""}">☷<span>${T.menuTab}</span></button></nav>${orderModal()}${dishModal()}`;bind()}
function openOrder(){const o=state.orders[state.selected];state.editor={date:state.selected,dishes:[...(o?.dishes||[])],note:o?.note||"",error:""};render()}
function bind(){document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>act(b.dataset.action));document.querySelectorAll("[data-date]").forEach(b=>b.onclick=()=>{state.selected=b.dataset.date;const d=fromKey(state.selected);if(d.getMonth()!==state.cursor.getMonth())state.cursor=new Date(d.getFullYear(),d.getMonth(),1,12);render()});document.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>{state.selected=b.dataset.jump;const d=fromKey(state.selected);state.cursor=new Date(d.getFullYear(),d.getMonth(),1,12);render()});document.querySelectorAll("[data-pick]").forEach(b=>b.onclick=()=>{const id=b.dataset.pick,e=state.editor;e.dishes=e.dishes.includes(id)?e.dishes.filter(x=>x!==id):[...e.dishes,id];render()});document.querySelectorAll("[data-edit-dish]").forEach(b=>b.onclick=()=>{const d=dish(b.dataset.editDish);state.dishEditor={...d,error:""};render()});document.querySelectorAll("[data-remove-dish]").forEach(b=>b.onclick=()=>{if(confirm(T.deleteDishConfirm)){state.menu=state.menu.filter(x=>x.id!==b.dataset.removeDish);persist();render()}});document.querySelectorAll("[data-emoji]").forEach(b=>b.onclick=()=>{state.dishEditor.emoji=b.dataset.emoji;render()});document.querySelector("#order-date")?.addEventListener("change",e=>state.editor.date=e.target.value);document.querySelector("#order-note")?.addEventListener("input",e=>state.editor.note=e.target.value);document.querySelector("#dish-name")?.addEventListener("input",e=>state.dishEditor.name=e.target.value);document.querySelector("#dish-detail")?.addEventListener("input",e=>state.dishEditor.detail=e.target.value)}
function act(a){if(a==="prev"||a==="next"){state.cursor=new Date(state.cursor.getFullYear(),state.cursor.getMonth()+(a==="next"?1:-1),1,12);render()}if(a==="today"){state.cursor=new Date(today.getFullYear(),today.getMonth(),1,12);state.selected=key(today);render()}if(a==="create"||a==="edit")openOrder();if(a==="cancel"){state.editor=null;render()}if(a==="save-order"){const e=state.editor;if(!e.dishes.length){e.error=T.chooseDishError;render();return}if(e.date!==state.selected)delete state.orders[state.selected];state.orders[e.date]={dishes:e.dishes,note:e.note.trim(),done:false};state.selected=e.date;const d=fromKey(e.date);state.cursor=new Date(d.getFullYear(),d.getMonth(),1,12);state.editor=null;persist();render()}if(a==="toggle"){state.orders[state.selected].done=!state.orders[state.selected].done;persist();render()}if(a==="delete"&&confirm(T.deleteConfirm)){delete state.orders[state.selected];persist();render()}if(a==="add-dish"){state.dishEditor={id:"",emoji:"🍽️",name:"",detail:"",error:""};render()}if(a==="cancel-dish"){state.dishEditor=null;render()}if(a==="save-dish"){const e=state.dishEditor;if(!e.name.trim()){e.error=T.dishNameRequired;render();return}if(e.id){const i=state.menu.findIndex(x=>x.id===e.id);state.menu[i]={id:e.id,emoji:e.emoji,name:e.name.trim(),detail:e.detail.trim()}}else state.menu.push({id:`dish-${Date.now()}`,emoji:e.emoji,name:e.name.trim(),detail:e.detail.trim()});state.dishEditor=null;persist();render()}}
document.addEventListener("click",event=>{if(event.target.closest('[data-action="go-menu"]')){state.editor=null;state.page="menu";render()}});
render();
