/* 直接修改引号里的文字，保存后重新上传 netlify 文件夹即可。 */
window.SITE_TEXT = {
  brand: "只属于你的菜单",
  brandEnglish: "OUR LITTLE KITCHEN",
  greeting: "我会为你做一辈子的🍚",
  subtitle: "把想吃的，写进我们的日子里。",
  calendarTab: "日程",
  menuTab: "菜单",
  newOrder: "点餐",
  calendarLabel: "用餐日历",
  today: "今天",
  pending: "害没吃呢",
  completed: "害嗨害!吃饱啦!!",
  calendarHint: "点击日期，记录想吃的饭饭",
  emptyTitle: "今天还没有安排",
  emptyBody: "想吃什么就记下来，日历会帮你记住。",
  createOrder: "记录一顿饭",
  pendingTitle: "这一天想吃这些",
  completedTitle: "这顿饭已经完成啦",
  noteLabel: "留给YAN大厨的话",
  defaultNote: "没有特别备注，按主厨心意来。",
  editOrder: "修改点餐",
  markCompleted: "确认完成",
  markPending: "改为待确认",
  deleteOrder: "删除这条记录",
  deleteConfirm: "确定删除这条点餐记录吗？",
  upcomingLabel: "COMING UP",
  upcomingTitle: "接下来的期待",
  upcomingEmpty: "还没有待办点餐，选个日子开始记录吧。",
  chefPreparing: "等待主厨准备中",
  orderEditorTitle: "想吃什么？",
  orderEditorLabel: "DINNER NOTE",
  dateLabel: "点餐日期",
  noteEditorLabel: "备注 / 悄悄话",
  notePlaceholder: "少辣、多一点香菜，或者想几点开饭…",
  chooseDishError: "请至少选择一道想吃的菜。",
  cancel: "取消",
  saveOrder: "保存到日历",
  menuTitle: "我的菜单",
  menuSubtitle: "把会做的、想吃的，都放进这里。",
  menuEmptyTitle: "还没有添加菜品",
  menuEmptyBody: "从一个喜欢的 Emoji 开始，创建属于你们自己的菜单。",
  addDish: "添加菜品",
  editDish: "编辑",
  deleteDish: "删除",
  dishName: "菜品名称",
  dishDescription: "一句简单介绍",
  chooseEmoji: "选择 Emoji",
  saveDish: "保存菜品",
  dishNameRequired: "请填写菜品名称。",
  deleteDishConfirm: "确定从菜单中删除这道菜吗？",
  footer: "与你一块的干饭日"
};
